language: rust
rust:
  - 1.0.0
env:
  global:
    - CARGO_MAKE_RUN_CODECOV="true"
cache: cargo
script:
  - cargo test
  - which cargo-make
  - cargo install cargo-make
  - which cargo-make || cargo install cargo-make
  - cargo make ci-flow
