version: 2.1
jobs:
  coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Coverage with docker
          command: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin
workflows:
  version: 2.1
  code_coverage:
    jobs:
      - coverage